### ISSUE TITLE
Unable to decode token

### ISSUE THREAD

**Issue by jweob** [maximebf/python-withings#14]
Thanks for creating this. I am using this on Python 3.4 with the following modified example code:

```
from withings import WithingsAuth, WithingsApi
from ApiKeys import CONSUMER_KEY, CONSUMER_SECRET

auth = WithingsAuth(CONSUMER_KEY, CONSUMER_SECRET)
authorize_url = auth.get_authorize_url()
print("Go to %s allow the app and copy your oauth_verifier" % authorize_url)

oauth_verifier = input('Please enter your oauth_verifier: ')
print(oauth_verifier)
creds = auth.get_credentials(oauth_verifier)

client = WithingsApi(creds)
measures = client.get_measures(limit=1)
print("Your last measured weight: %skg" % measures[0].weight)
```

I get the authorization url and can follow the prompts to get to a page which has 

```
Access granted
oauth_token=831261652e38dc071cc0f98997f7f6ebce766f3de43bb5c198e87c3f&oauth_verifier=jo9Ic2OpohhWxU  
```

When I enter this token at the prompt I get the following error. Any ideas what is going wrong?

<pre>
Traceback (most recent call last):
  File "/Users/jweob/Library/Python/3.4/lib/python/site-packages/requests_oauthlib/oauth1_session.py", line 348, in _fetch_token
    token = dict(urldecode(r.text))
  File "/Users/jweob/Library/Python/3.4/lib/python/site-packages/requests_oauthlib/oauth1_session.py", line 33, in urldecode
    return json.loads(body)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jweob/PyCharmProjects/FatPi/Withings.py", line 11, in <module>
    creds = auth.get_credentials(oauth_verifier)
  File "/Users/jweob/Library/Python/3.4/lib/python/site-packages/withings/__init__.py", line 78, in get_credentials
    tokens = oauth.fetch_access_token('%s/access_token' % self.URL)
  File "/Users/jweob/Library/Python/3.4/lib/python/site-packages/requests_oauthlib/oauth1_session.py", line 297, in fetch_access_token
    token = self._fetch_token(url)
  File "/Users/jweob/Library/Python/3.4/lib/python/site-packages/requests_oauthlib/oauth1_session.py", line 354, in _fetch_token
    raise ValueError(error)
ValueError: Unable to decode token from token response. This is commonly caused by an unsuccessful request where a non urlencoded error message is returned. The decoding error was Expecting value: line 1 column 1 (char 0)

Process finished with exit code 1
</pre>

**Comment by jweob** [comment]
Sorry I was being dense - I missed that the oauth verifier is tacked on to the oauth token
