### ISSUE TITLE
auth.get_credentials ERROR Missing access token parameter.

### ISSUE THREAD

**Issue by ethanopp** [maximebf/python-withings#23]
Documented usage is not working on the following line
`creds = auth.get_credentials(authorization_response)`
in
```
redirect_uri = 'https://fit.XXXX.com/pages/authorize/withings'
client_id = 'XXXX'
client_secret = 'XXXX'

from nokia import NokiaAuth, NokiaApi

auth = NokiaAuth(client_id, client_secret, callback_uri=redirect_uri)
authorize_url = auth.get_authorize_url()
print("Go to %s allow the app and copy the url you are redirected to." % authorize_url)
authorization_response = input('Please enter your full authorization response url: ')
creds = auth.get_credentials(authorization_response)

client = NokiaApi(creds)
measures = client.get_measures(limit=1)
print("Your last measured weight: %skg" % measures[0].weight)

creds = client.get_credentials()
```

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.3.1\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.3.1\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/Ethan/PycharmProjects/fitness/pages/pandasTesting.py", line 18, in <module>
    creds = auth.get_credentials(authorization_response)
  File "C:\Users\Ethan\PycharmProjects\fitness\venv\lib\site-packages\nokia\__init__.py", line 86, in get_credentials
    client_secret=self.consumer_secret)
  File "C:\Users\Ethan\PycharmProjects\fitness\venv\lib\site-packages\requests_oauthlib\oauth2_session.py", line 244, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "C:\Users\Ethan\PycharmProjects\fitness\venv\lib\site-packages\oauthlib\oauth2\rfc6749\clients\base.py", line 415, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "C:\Users\Ethan\PycharmProjects\fitness\venv\lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 425, in parse_token_response
    validate_token_parameters(params)
  File "C:\Users\Ethan\PycharmProjects\fitness\venv\lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 435, in validate_token_parameters
    raise MissingTokenError(description="Missing access token parameter.")
oauthlib.oauth2.rfc6749.errors.MissingTokenError: (missing_token) Missing access token parameter.
```

**Comment by ethanopp** [comment]
Figured out what was going on... Documentation says to pass full url, really only the code should be getting passed....
